version: '3.8'

services:
  # PostgreSQL Database Only
  postgres:
    image: postgres:15-alpine
    container_name: spacs_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-spacs_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-spacs_secure_password_2025}
      POSTGRES_DB: ${POSTGRES_DB:-spacs_africa}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./shared/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spacs_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spacs_user -d spacs_africa"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache & Message Broker Only
  redis:
    image: redis:7-alpine
    container_name: spacs_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spacs_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes
    restart: unless-stopped

networks:
  spacs_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
